import assert from 'node:assert/strict';
import test from 'node:test';
import {
  classifyDepartment,
  CORAL_RIDGE_DEPARTMENTS,
  OVIEDO_DEEP_LAKE_DEPARTMENTS,
  parseItemLine,
} from '../routecart-classifier';

const CASES: Array<[string, string]> = [
  ["Shampoo", "Personal Care"],
  ["Milk", "Dairy"],
  ["Frozen pizza", "Frozen"],
  ["Dog food", "Pets"],
  ["Coca-Cola", "Snacks & Bev"],
  ["Bananas", "Fresh Produce"],
  ["Eggs", "Dairy"],
  ["Phone charger", "Electronics"],
  ["Paper towels", "Household Paper"],
  ["Ice cream", "Frozen"],
  ["Womens Clothes", "Womens"],
  ["Party Supplies", "Party Supplies"],
  ["womens black hoodie", "Womens"],
  ["paper towel", "Household Paper"],
  ["usb c phone charger", "Electronics"],
  ["birthday balloons", "Party Supplies"],
  ["toilet tissue", "Household Paper"],
  ["coke cans", "Snacks & Bev"],
  ["dog treats x3", "Pets"],
  ["2x whole milk", "Dairy"],
  ["shower curtains", "Bath & Shower"],
  ["dryer sheet", "Laundry"],
  ["mens black jeans", "Mens"],
  ["baby formula", "Baby"],
  ["chicken breasts", "Meat & Seafood"],
  ["printer paper", "Office Supplies"],
  ["christmas lights", "Seasonal"],
  ["face moisturizer", "Beauty"],
  ["car motor oil", "Auto"],
  ["bathroom towels", "Bath & Shower"],
  ["strawberries (2)", "Fresh Produce"],
  ["paper napkins", "Household Paper"],
  ["facial tissue", "Household Paper"],
  ["dishwashing liquid", "Cleaning"],
  ["garbage bags", "Cleaning"],
  ["fabric softener", "Laundry"],
  ["shower mat", "Bath & Shower"],
  ["bed pillow", "Bedding"],
  ["storage container", "Home"],
  ["women jeans", "Womens"],
  ["men shorts", "Mens"],
  ["girls leggings", "Girls"],
  ["boys sneakers", "Shoes"],
  ["birthday banner", "Party Supplies"],
  ["holiday lights", "Seasonal"],
  ["phone screen protector", "Electronics"],
  ["wireless earbuds", "Electronics"],
  ["cat treats", "Pets"],
  ["dog toy", "Pets"],
  ["frozen waffles", "Frozen"],
  ["sliced turkey", "Deli"],
  ["olive oil", "Grocery"],
  ["vitamin c", "Health"],
  ["face wash", "Beauty"],
  ["paint brushes", "Paint"],
  ["car battery", "Auto"],
  ["toilet cleaning spray", "Cleaning"],
  ["laundry hamper", "Laundry"],
  ["paper plates", "Household Paper"],
  ["women running shoes", "Shoes"],
  ["mens underwear", "Intimates"],
  ["girls sneakers", "Shoes"],
  ["boys hoodie", "Boys"],
  ["birthday streamers", "Party Supplies"],
  ["christmas wrapping paper", "Seasonal"],
  ["baby shampoo", "Baby"],
  ["dog shampoo", "Pets"],
  ["gaming mouse", "Electronics"],
  ["school folders", "Office Supplies"],
  ["craft glitter", "Arts & Crafts"],
  ["kitchen knives", "Kitchen"],
  ["coffee maker", "Kitchen"],
  ["throw blanket", "Bedding"],
  ["bathroom rug", "Bath & Shower"],
  ["cough medicine", "Health"],
  ["frozen french fries", "Frozen"],
  ["fresh tomatoes", "Fresh Produce"],
  ["chicken thighs", "Meat & Seafood"],
  ["cupcake tray", "Kitchen"],
  ["car windshield wipers", "Auto"],
  ["AA batteries", "Electronics"],
  ["scented candles", "Home"],
  ["hand soap", "Personal Care"],
  ["body lotion", "Personal Care"],
  ["bath towel set", "Bath & Shower"],
  ["plastic storage bins", "Home"],
  ["air freshener", "Cleaning"],
  ["aluminum foil", "Kitchen"],
  ["ziplock bags", "Kitchen"],
  ["dish sponge", "Cleaning"],
  ["oven mitts", "Kitchen"],
  ["coffee filters", "Kitchen"],
  ["birthday plates", "Party Supplies"],
  ["school backpack", "Office Supplies"],
  ["women socks", "Womens"],
  ["mens belt", "Mens"],
  ["girls hair accessories", "Girls"],
  ["boys underwear", "Intimates"],
  ["baby blanket", "Baby"],
  ["dog vitamins", "Pets"],
  ["cat shampoo", "Pets"],
  ["frozen chicken nuggets", "Frozen"],
  ["fresh garlic", "Fresh Produce"],
  ["deli cheese", "Deli"],
  ["cake decorating kit", "Arts & Crafts"],
  ["batteries", "Electronics"],
  ["candles", "Home"],
  ["soap", "Personal Care"],
  ["towels", "Bath & Shower"],
  ["storage box", "Home"],
  ["trash can", "Home"],
  ["light bulbs", "Hardware"],
  ["extension cord", "Hardware"],
  ["phone case", "Electronics"],
  ["hair brush", "Beauty"],
  ["face cream", "Beauty"],
  ["baby clothes", "Baby"],
  ["dog bed", "Pets"],
  ["cat litter box", "Pets"],
  ["frozen fruit", "Frozen"],
  ["fresh chicken", "Meat & Seafood"],
  ["sandwich bread", "Bakery"],
  ["birthday decorations", "Party Supplies"],
  ["school notebook", "Office Supplies"],
  ["women jacket", "Womens"],
  ["mens socks", "Mens"],
  ["kids shoes", "Shoes"],
  ["car air freshener", "Auto"],
  ["paint tray", "Paint"],
  ["garden gloves", "Garden"],
  ["Tylenol", "Health"],
  ["Crest toothpaste", "Personal Care"],
  ["Dove body wash", "Personal Care"],
  ["Clorox wipes", "Cleaning"],
  ["Febreze", "Cleaning"],
  ["Duracell batteries", "Electronics"],
  ["AirPods case", "Electronics"],
  ["HDMI cable", "Electronics"],
  ["Crayola markers", "Office Supplies"],
  ["Elmers glue", "Arts & Crafts"],
  ["Nike socks", "Shoes"],
  ["baby socks", "Baby"],
  ["dog collar", "Pets"],
  ["cat bed", "Pets"],
  ["red roses", "Garden"],
  ["birthday gift bag", "Party Supplies"],
  ["Christmas ornaments", "Seasonal"],
  ["frying oil", "Grocery"],
  ["frozen burritos", "Frozen"],
  ["ground turkey", "Meat & Seafood"],
  ["sliced cheddar", "Deli"],
  ["paper bowls", "Household Paper"],
  ["hand towels", "Bath & Shower"],
  ["car wax", "Auto"],
  ["LED flashlight", "Hardware"],
  ["toilet papr", "Household Paper"],
  ["dish spnge", "Cleaning"],
  ["womens hoodi", "Womens"],
  ["mens tshirt", "Mens"],
  ["usb c cord", "Electronics"],
  ["phone chargerr", "Electronics"],
  ["coke 12pk", "Snacks & Bev"],
  ["frozen pizz", "Frozen"],
  ["dog treets", "Pets"],
  ["cat liter", "Pets"],
  ["baby wipes", "Baby"],
  ["laundry detergnt", "Laundry"],
  ["bath towls", "Bath & Shower"],
  ["shower curtan", "Bath & Shower"],
  ["bday balloons", "Party Supplies"],
  ["christmas decor", "Seasonal"],
  ["printer papr", "Office Supplies"],
  ["notebok", "Office Supplies"],
  ["hairbrush", "Beauty"],
  ["face moisturizr", "Beauty"],
  ["ground beaf", "Meat & Seafood"],
  ["chiken breast", "Meat & Seafood"],
  ["strawbery", "Fresh Produce"],
  ["icecream", "Frozen"],
  ["car batttery", "Auto"],
  ["cream", "Grocery"],
  ["oil", "Grocery"],
  ["wipes", "Baby"],
  ["bags", "Grocery"],
  ["lights", "Hardware"],
  ["brush", "Beauty"],
  ["charger", "Electronics"],
  ["socks", "Shoes"],
  ["flowers", "Garden"],
  ["paper", "Office Supplies"],
  ["shoes", "Shoes"],
  ["paint", "Paint"],
  ["gloves", "Garden"],
  ["blanket", "Bedding"],
  ["detergent", "Laundry"],
  ["cable", "Electronics"],
  ["decorations", "Home"],
  ["cheese", "Dairy"],
  ["laundry detergent", "Laundry"],
  ["bath towels", "Bath & Shower"],
  ["birthday candles", "Party Supplies"],
  ["ground beef", "Meat & Seafood"],
  ["garden hose", "Garden"],
  ["toilet paper", "Household Paper"],
  ["dish soap", "Cleaning"]
];

function expectedForCoralRidge(expected: string) {
  return expected === 'Snacks & Bev' ? 'Snacks & Beverages' : expected;
}

for (const [input, expected] of CASES) {
  test(`Oviedo: ${input} -> ${expected}`, () => {
    assert.equal(
      classifyDepartment(input, OVIEDO_DEEP_LAKE_DEPARTMENTS).department,
      expected,
    );
  });

  test(`Coral Ridge: ${input}`, () => {
    assert.equal(
      classifyDepartment(input, CORAL_RIDGE_DEPARTMENTS).department,
      expectedForCoralRidge(expected),
    );
  });
}

test('quantity parser handles trailing xN', () => {
  assert.deepEqual(parseItemLine('Dog treats x3'), {
    name: 'Dog treats',
    quantity: 3,
  });
});

test('quantity parser handles parenthesized quantity', () => {
  assert.deepEqual(parseItemLine('Ice cream (2)'), {
    name: 'Ice cream',
    quantity: 2,
  });
});

test('quantity parser leaves ordinary items unchanged', () => {
  assert.deepEqual(parseItemLine('Paper towels'), {
    name: 'Paper towels',
    quantity: undefined,
  });
});
